- name: Check if flag file exists
  stat:
    path: /home/pi/.ansible/.machine-id-reset
  register: flag

- name: Remove /etc/machine-id
  file:
    path: /etc/machine-id
    state: absent
  when: flag.stat.exists == False

- name: Remove /var/lib/dbus/machine-id
  file:
    path: /var/lib/dbus/machine-id
    state: absent
  when: flag.stat.exists == False

- name: Generate new machine-id
  command: systemd-machine-id-setup
  when: flag.stat.exists == False

- name: Touch flag file
  file:
    path: /home/pi/.ansible/.machine-id-reset
    state: touch
  when: flag.stat.exists == False
